### ISSUE TITLE
A couple of typos prevent to use the skill "as is"

### ISSUE THREAD

**Issue by sebsto** [alexa/skill-sample-nodejs-buttons-colorchanger#2]
**RollCall : 225** 
https://github.com/alexa/skill-sample-nodejs-buttons-colorchanger/blob/master/lambda/custom/rollcall.js#L225 

inputEvents => gameInputEvents 

**GamePlay : 78** 
https://github.com/alexa/skill-sample-nodejs-buttons-colorchanger/blob/master/lambda/custom/gameplay.js#L78

COLOR_SHADED => COLOR_ALLOWED

and COLOR_ALLOWED is a an array, so the array must be changed into an object at 
https://github.com/alexa/skill-sample-nodejs-buttons-colorchanger/blob/master/lambda/custom/settings.js#L40

**GamePlay : 152 & 154** : Typo for DEFAULT ...
https://github.com/alexa/skill-sample-nodejs-buttons-colorchanger/blob/master/lambda/custom/gameplay.js#L152
https://github.com/alexa/skill-sample-nodejs-buttons-colorchanger/blob/master/lambda/custom/gameplay.js#L154

**Comment by sebsto** [comment]
Looks like these issues are addressed by https://github.com/alexa/skill-sample-nodejs-buttons-colorchanger/pull/1

**Comment by mdinescu** [comment]
Thanks Sébastien! We have fixed the issues with an earlier pull request.

I appreciate your lending a hand to identify and close these issues!
