### ISSUE TITLE
Error when saying "Alexa Stop"

### ISSUE THREAD

**Issue by dustinbahr** [alexa/skill-sample-nodejs-buttons-colorchanger#3]
If you try to stop the skill by saying "Alexa Stop", an error occurs.

See attached log for the Events and Responses that are logged.

[StopIntentError.txt](https://github.com/alexa/skill-sample-nodejs-buttons-colorchanger/files/2124307/StopIntentError.txt)

**Comment by mdinescu** [comment]
I apologize for not commenting on this earlier. The issue has been resolved in this commit: https://github.com/alexa/skill-sample-nodejs-buttons-colorchanger/commit/060caa2870b7a46cabaa611394fc7fc648cd0afc
